// Register
export const USER_REGISTRATION_LOADING=`USER_REGISTRATION_LOADING`;
export const USER_REGISTRATION_SUCCESS=`USER_REGISTRATION_SUCCESS`;
export const USER_REGISTRATION_FAILED=`USER_REGISTRATION_FAILED`;


//  Login 
export const USER_LOGIN_LOADING=`USER_LOGIN_LOADING`;
export const USER_LOGIN_SUCCESS=`USER_LOGIN_SUCCESS`;
export const USER_LOGIN_FAILED=`USER_LOGIN_FAILED`;

//  logOut
export const USER_LOG_OUT="USER_LOG_OUT"