
export const GETING_USER_INFO_LOADING=`GETING_USER_INFO_LOADING`;
export const GETING_USER_INFO_SUCCESS=`GETING_USER_INFO_SUCCESS`;
export const GETING_USER_INFO_FAILED=`GETING_USER_INFO_FAILED`;




